Due to a typo on the mappings of satellite glial cells, its markers will need a re-do on our end. Oops.

In [55]:
import pandas as pd 
from wikidata2df import wikidata2df

gene_reference = pd.read_csv("../results/human_gene_reference_from_panglao_to_wikidata_04_11_2020.csv")

cell_type_reference = pd.read_csv("../results/cell_type_reference_from_panglao_to_wikidata_31_10_2020.csv")

markers = pd.read_csv("../data/PanglaoDB_markers_27_Mar_2020.tsv", sep="\t")

query = """
SELECT ?item ?itemLabel ?superclass
WHERE
{
?item wdt:P31 wd:Q189118. 
?item wdt:P279 ?superclass. 
?superclass  wdt:P31 wd:Q189118. # cell type
?item wdt:P703 wd:Q15978631. # human cell type
SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
"""

dataframe_to_join = wikidata2df(query)

cell_type_reference = cell_type_reference.merge(dataframe_to_join, left_on="wikidata", right_on="superclass")

In [5]:
markers = markers.dropna(subset=["species"])
human_markers = markers[["Hs" in val for val in markers["species"]]]
human_markers_lean = human_markers[["official gene symbol", "cell type"]]

human_markers_lean = human_markers_lean.merge(cell_type_reference, left_on="cell type", right_on="panglao")[["official gene symbol", "cell type", "item"]]

human_markers_lean.columns = ["official gene symbol", "cell type", "cell type id"]
human_markers_lean = human_markers_lean.merge(gene_reference, left_on="official gene symbol", right_on="panglao")[["official gene symbol", "cell type", "cell type id", "wikidata"]]

human_markers_lean.columns = ["official gene symbol", "cell type (general)", "cell type id (human)", "gene id"]
human_markers_lean = human_markers_lean.drop_duplicates()
human_markers_lean

,official gene symbol,cell type (general),cell type id (human),gene id
0,CTRB1,Acinar cells,Q101405107,Q17911638
1,CTRB1,Enterocytes,Q101405073,Q17911638
2,KLK1,Acinar cells,Q101405107,Q18028299
3,KLK1,Distal tubule cells,Q101405088,Q18028299
4,KLK1,Endothelial cells,Q68621315,Q18028299
...,...,...,...,...
10488,SLC14A1,Urothelial cells,Q101404883,Q18031563
10489,UPK3A,Urothelial cells,Q101404883,Q18032295
10490,UPK1A,Urothelial cells,Q101404883,Q18036055
10491,UPK2,Urothelial cells,Q101404883,Q18032294
10492,UPK3B,Urothelial cells,Q101404883,Q20800734

In [22]:
from wikibaseintegrator import wbi_login, WikibaseIntegrator
from wikibaseintegrator.wbi_enums import ActionIfExists
from wikibaseintegrator.wbi_config import config as wbi_config
from getpass import getpass

wbi_config['USER_AGENT'] = 'MyWikibaseBot/1.0 (https://www.wikidata.org/wiki/User:MyUsername)'

WBUSER = getpass(prompt="username:")  
WBPASS = getpass(prompt='Enter your password: ')  
login_instance = wbi_login.Clientlogin(user=WBUSER, password=WBPASS)

In [23]:
wbi = WikibaseIntegrator(login=login_instance)

In [30]:
from wikibaseintegrator.datatypes import Item, URL, Time
from wikibaseintegrator.wbi_enums import WikibaseDatePrecision

data = []
for i, row in human_markers_lean.iterrows():
    if row["cell type (general)"] == "Satellite glial cells":
      item = wbi.item.get(entity_id=row["cell type id (human)"])
      s = row["cell type id (human)"]
      p = "P8872"
      o = row["gene id"]
      r1 = "P813"
      or1 = "+2020-11-27T00:00:00Z"
      r2 = "P854"
      or2 = 'https://panglaodb.se/markers.html'
      r3 = "P248"
      or3 = "Q99936939"


      references = [
        [
            Time(time=or1, prop_nr=r1, precision=WikibaseDatePrecision.DAY),
                     URL(value=or2, prop_nr=r2),
                     Item(value=or3, prop_nr=r3)
        ]
    ]

      marker_statement = Item(value= o, prop_nr=p, references=references)
      data.append(marker_statement)


item.claims.add(data)
item.write()

<ItemEntity @c1a250 _BaseEntity__api=<wikibaseintegrator.wikibaseintegrator.WikibaseIntegrator object at 0x7fb49601c910>
	 _BaseEntity__title='Q101404951'
	 _BaseEntity__pageid=98726744
	 _BaseEntity__lastrevid=2121472022
	 _BaseEntity__type='item'
	 _BaseEntity__id='Q101404951'

In [59]:
import pandas as pd 
from wikidata2df import wikidata2df

gene_reference = pd.read_csv("../results/human_gene_reference_from_panglao_to_wikidata_04_11_2020.csv")

cell_type_reference = pd.read_csv("../results/cell_type_reference_from_panglao_to_wikidata_31_10_2020.csv")

markers = pd.read_csv("../data/PanglaoDB_markers_27_Mar_2020.tsv", sep="\t")

query = """
SELECT ?item ?itemLabel ?superclass
WHERE
{
?item wdt:P31 wd:Q189118. 
?item wdt:P279 ?superclass. 
?superclass  wdt:P31 wd:Q189118. # cell type
?item wdt:P703 wd:Q83310. # human cell type
SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
"""

dataframe_to_join = wikidata2df(query)

cell_type_reference = cell_type_reference.merge(dataframe_to_join, left_on="wikidata", right_on="superclass")

markers = markers.dropna(subset=["species"])  
mouse_markers = markers[["Mm" in val for val in markers["species"]]]
mouse_markers_lean = mouse_markers[["official gene symbol", "cell type"]]
mouse_markers_lean = mouse_markers_lean.merge(cell_type_reference, left_on="cell type", right_on="panglao")[["official gene symbol", "cell type", "item"]]
mouse_markers_lean.columns = ["official gene symbol", "cell type", "cell type id"]

mouse_gene_reference = pd.read_csv("../results/mouse_gene_reference_from_panglao_to_wikidata_22_12_2020.csv")

mouse_markers_lean = mouse_markers_lean.merge(mouse_gene_reference, left_on="official gene symbol", right_on="official gene symbol")

mouse_markers_lean

      official gene symbol         cell type cell type id       item
0                    CTRB1      Acinar cells   Q104416307  Q18261856
1                    CTRB1      Acinar cells   Q104416307  Q18261856
2                    CTRB1       Enterocytes   Q104416276  Q18261856
3                    CTRB1       Enterocytes   Q104416276  Q18261856
4                     KLK1      Acinar cells   Q104416307  Q18251870
...                    ...               ...          ...        ...
34757              SLC14A1  Urothelial cells   Q104416156  Q18272870
34758                UPK3A  Urothelial cells   Q104416156  Q18255259
34759                UPK1A  Urothelial cells   Q104416156  Q18273793
34760                 UPK2  Urothelial cells   Q104416156  Q18255258
34761                UPK3B  Urothelial cells   Q104416156  Q18271264

[34762 rows x 4 columns]

In [66]:
from tqdm import tqdm  # Import tqdm for the progress bar functionality

cell_types_to_process = ["Acinar cells", "Satellite glial cells", "Clara cells"]
# Group data by 'cell type'
grouped_data = mouse_markers_lean.groupby('cell type')

for cell_type, group in tqdm(grouped_data, desc="Initializing..."):
    tqdm.write(f"Processing Cell Type: {cell_type}")  # Print current cell type being processed
    
    data = []  # Reset data for each cell type
    for i, row in group.iterrows():
        p = "P8872"
        o = row["item"]
        r1 = "P813"
        or1 = "+2020-11-27T00:00:00Z"
        r2 = "P854"
        or2 = 'https://panglaodb.se/markers.html'
        r3 = "P248"
        or3 = "Q99936939"

        references = [
            [
                Time(time=or1, prop_nr=r1, precision=WikibaseDatePrecision.DAY),
                URL(value=or2, prop_nr=r2),
                Item(value=or3, prop_nr=r3)
            ]
        ]

        marker_statement = Item(value=o, prop_nr=p, references=references)
        data.append(marker_statement)

    # Now, outside the loop for the current cell type group
    if data:
        # Assuming `item` is already the correct Wikidata item for the current cell type
        item = wbi.item.get(entity_id=row["cell type id"])
        item.claims.add(data, ActionIfExists.APPEND_OR_REPLACE)
        item.write()

Initializing...:   0%|          | 0/163 [00:00<?, ?it/s]

Processing Cell Type: Acinar cells

Initializing...:   1%|          | 1/163 [00:01<03:34,  1.32s/it]

Processing Cell Type: Adipocyte progenitor cells

Initializing...:   1%|          | 2/163 [00:02<02:39,  1.01it/s]

Processing Cell Type: Adipocytes

Initializing...:   2%|▏         | 3/163 [00:04<03:46,  1.42s/it]

Processing Cell Type: Adrenergic neurons

Initializing...:   2%|▏         | 4/163 [00:04<03:02,  1.15s/it]

Processing Cell Type: Airway epithelial cells

Initializing...:   3%|▎         | 5/163 [00:05<02:30,  1.05it/s]

Processing Cell Type: Airway goblet cells

Initializing...:   4%|▎         | 6/163 [00:06<02:26,  1.07it/s]

Processing Cell Type: Airway smooth muscle cells

Initializing...:   4%|▍         | 7/163 [00:06<02:06,  1.23it/s]

Processing Cell Type: Alpha cells

Initializing...:   5%|▍         | 8/163 [00:08<02:27,  1.05it/s]

Processing Cell Type: Alveolar macrophages

Initializing...:   6%|▌         | 9/163 [00:08<02:22,  1.08it/s]

Processing Cell Type: Astrocytes

Initializing...:   6%|▌         | 10/163 [00:10<02:37,  1.03s/it]

Processing Cell Type: B cells

Initializing...:   7%|▋         | 11/163 [00:11<02:59,  1.18s/it]

Processing Cell Type: B cells memory

Initializing...:   7%|▋         | 12/163 [00:12<02:52,  1.14s/it]

Processing Cell Type: B cells naive

Initializing...:   8%|▊         | 13/163 [00:13<02:42,  1.08s/it]

Processing Cell Type: Basal cells

Initializing...:   9%|▊         | 14/163 [00:14<02:35,  1.04s/it]

Processing Cell Type: Basophils

Initializing...:   9%|▉         | 15/163 [00:15<02:39,  1.08s/it]

Processing Cell Type: Beta cells

Initializing...:  10%|▉         | 16/163 [00:16<02:34,  1.05s/it]

Processing Cell Type: Cajal-Retzius cells

Initializing...:  10%|█         | 17/163 [00:18<02:44,  1.13s/it]

Processing Cell Type: Cardiac stem and precursor cells

Initializing...:  11%|█         | 18/163 [00:18<02:24,  1.01it/s]

Processing Cell Type: Cardiomyocytes

Initializing...:  12%|█▏        | 19/163 [00:20<02:47,  1.17s/it]

Processing Cell Type: Cholangiocytes

Initializing...:  12%|█▏        | 20/163 [00:21<02:50,  1.19s/it]

Processing Cell Type: Cholinergic neurons

Initializing...:  13%|█▎        | 21/163 [00:22<02:23,  1.01s/it]

Processing Cell Type: Chondrocytes

Initializing...:  13%|█▎        | 22/163 [00:23<02:24,  1.02s/it]

Processing Cell Type: Ciliated cells

Initializing...:  14%|█▍        | 23/163 [00:23<02:08,  1.09it/s]

Processing Cell Type: Clara cells

Initializing...:  15%|█▍        | 24/163 [00:24<02:09,  1.08it/s]

Processing Cell Type: Crypt cells

Initializing...:  15%|█▌        | 25/163 [00:25<01:56,  1.18it/s]

Processing Cell Type: Decidual cells

Initializing...:  16%|█▌        | 26/163 [00:26<01:45,  1.29it/s]

Processing Cell Type: Delta cells

Initializing...:  17%|█▋        | 27/163 [00:27<01:52,  1.20it/s]

Processing Cell Type: Dendritic cells

Initializing...:  17%|█▋        | 28/163 [00:28<02:14,  1.01it/s]

Processing Cell Type: Distal tubule cells

Initializing...:  18%|█▊        | 29/163 [00:29<02:10,  1.03it/s]

Processing Cell Type: Ductal cells

Initializing...:  18%|█▊        | 30/163 [00:30<02:06,  1.05it/s]

Processing Cell Type: Embryonic stem cells

Initializing...:  19%|█▉        | 31/163 [00:31<02:08,  1.03it/s]

Processing Cell Type: Endothelial cells

Initializing...:  20%|█▉        | 32/163 [00:33<02:39,  1.22s/it]

Processing Cell Type: Endothelial cells (aorta)

Initializing...:  20%|██        | 33/163 [00:34<02:46,  1.28s/it]

Processing Cell Type: Endothelial cells (blood brain barrier)

Initializing...:  21%|██        | 34/163 [00:35<02:24,  1.12s/it]

Processing Cell Type: Enteric glia cells

Initializing...:  21%|██▏       | 35/163 [00:35<02:04,  1.03it/s]

Processing Cell Type: Enteric neurons

Initializing...:  22%|██▏       | 36/163 [00:37<02:12,  1.05s/it]

Processing Cell Type: Enterochromaffin cells

Initializing...:  23%|██▎       | 37/163 [00:37<01:55,  1.09it/s]

Processing Cell Type: Enterocytes

Initializing...:  23%|██▎       | 38/163 [00:39<02:16,  1.09s/it]

Processing Cell Type: Enteroendocrine cells

Initializing...:  24%|██▍       | 39/163 [00:40<02:07,  1.03s/it]

Processing Cell Type: Eosinophils

Initializing...:  25%|██▍       | 40/163 [00:40<01:53,  1.08it/s]

Processing Cell Type: Ependymal cells

Initializing...:  25%|██▌       | 41/163 [00:42<02:07,  1.04s/it]

Processing Cell Type: Epiblast cells

Initializing...:  26%|██▌       | 42/163 [00:42<01:49,  1.10it/s]

Processing Cell Type: Epithelial cells

Initializing...:  26%|██▋       | 43/163 [00:44<02:37,  1.31s/it]

Processing Cell Type: Epsilon cells

Initializing...:  27%|██▋       | 44/163 [00:45<02:21,  1.19s/it]

Processing Cell Type: Erythroid-like and erythroid precursor cells

Initializing...:  28%|██▊       | 45/163 [00:47<02:21,  1.20s/it]

Processing Cell Type: Fibroblasts

Initializing...:  28%|██▊       | 46/163 [00:48<02:44,  1.40s/it]

Processing Cell Type: Follicular cells

Initializing...:  29%|██▉       | 47/163 [00:49<02:17,  1.18s/it]

Processing Cell Type: Foveolar cells

Initializing...:  29%|██▉       | 48/163 [00:50<02:01,  1.05s/it]

Processing Cell Type: GABAergic neurons

Initializing...:  30%|███       | 49/163 [00:51<01:45,  1.08it/s]

Processing Cell Type: Gamma (PP) cells

Initializing...:  31%|███       | 50/163 [00:51<01:43,  1.10it/s]

Processing Cell Type: Gamma delta T cells

Initializing...:  31%|███▏      | 51/163 [00:52<01:47,  1.04it/s]

Processing Cell Type: Gastric chief cells

Initializing...:  32%|███▏      | 52/163 [00:53<01:35,  1.16it/s]

Processing Cell Type: Germ cells

Initializing...:  33%|███▎      | 53/163 [00:55<02:14,  1.22s/it]

Processing Cell Type: Glutaminergic neurons

Initializing...:  33%|███▎      | 54/163 [00:56<01:52,  1.03s/it]

Processing Cell Type: Glycinergic neurons

Initializing...:  34%|███▎      | 55/163 [00:56<01:40,  1.08it/s]

Processing Cell Type: Goblet cells

Initializing...:  34%|███▍      | 56/163 [00:57<01:40,  1.06it/s]

Processing Cell Type: Granulosa cells

Initializing...:  35%|███▍      | 57/163 [00:58<01:30,  1.17it/s]

Processing Cell Type: Hemangioblasts

Initializing...:  36%|███▌      | 58/163 [00:59<01:18,  1.34it/s]

Processing Cell Type: Hematopoietic stem cells

Initializing...:  36%|███▌      | 59/163 [01:00<01:34,  1.10it/s]

Processing Cell Type: Hepatic stellate cells

Initializing...:  37%|███▋      | 60/163 [01:01<01:35,  1.08it/s]

Processing Cell Type: Hepatoblasts

Initializing...:  37%|███▋      | 61/163 [01:02<01:27,  1.16it/s]

Processing Cell Type: Hepatocytes

Initializing...:  38%|███▊      | 62/163 [01:03<01:52,  1.12s/it]

Processing Cell Type: His bundle cells

Initializing...:  39%|███▊      | 63/163 [01:04<01:35,  1.05it/s]

Processing Cell Type: Immature neurons

Initializing...:  39%|███▉      | 64/163 [01:05<01:32,  1.07it/s]

Processing Cell Type: Intercalated cells

Initializing...:  40%|███▉      | 65/163 [01:06<01:31,  1.07it/s]

Processing Cell Type: Interneurons

Initializing...:  40%|████      | 66/163 [01:08<02:13,  1.38s/it]

Processing Cell Type: Ionocytes

Initializing...:  41%|████      | 67/163 [01:09<01:49,  1.14s/it]

Processing Cell Type: Juxtaglomerular cells

Initializing...:  42%|████▏     | 68/163 [01:09<01:31,  1.03it/s]

Processing Cell Type: Keratinocytes

Initializing...:  42%|████▏     | 69/163 [01:10<01:31,  1.03it/s]

Processing Cell Type: Kidney progenitor cells

Initializing...:  43%|████▎     | 70/163 [01:11<01:20,  1.15it/s]

Processing Cell Type: Kupffer cells

Initializing...:  44%|████▎     | 71/163 [01:12<01:20,  1.14it/s]

Processing Cell Type: Langerhans cells

Initializing...:  44%|████▍     | 72/163 [01:12<01:11,  1.26it/s]

Processing Cell Type: Leydig cells

Initializing...:  45%|████▍     | 73/163 [01:13<01:16,  1.17it/s]

Processing Cell Type: Loop of Henle cells

Initializing...:  45%|████▌     | 74/163 [01:14<01:17,  1.14it/s]

Processing Cell Type: Luminal epithelial cells

Initializing...:  46%|████▌     | 75/163 [01:15<01:14,  1.18it/s]

Processing Cell Type: Macrophages

Initializing...:  47%|████▋     | 76/163 [01:17<01:48,  1.25s/it]

Processing Cell Type: Mammary epithelial cells

Initializing...:  47%|████▋     | 77/163 [01:18<01:39,  1.16s/it]

Processing Cell Type: Mast cells

Initializing...:  48%|████▊     | 78/163 [01:20<01:56,  1.37s/it]

Processing Cell Type: Megakaryocytes

Initializing...:  48%|████▊     | 79/163 [01:21<01:52,  1.34s/it]

Processing Cell Type: Melanocytes

Initializing...:  49%|████▉     | 80/163 [01:22<01:40,  1.22s/it]

Processing Cell Type: Meningeal cells

Initializing...:  50%|████▉     | 81/163 [01:23<01:25,  1.04s/it]

Processing Cell Type: Merkel cells

Initializing...:  50%|█████     | 82/163 [01:23<01:14,  1.09it/s]

Processing Cell Type: Mesangial cells

Initializing...:  51%|█████     | 83/163 [01:25<01:20,  1.00s/it]

Processing Cell Type: Mesothelial cells

Initializing...:  52%|█████▏    | 84/163 [01:26<01:19,  1.01s/it]

Processing Cell Type: Microfold cells

Initializing...:  52%|█████▏    | 85/163 [01:26<01:11,  1.10it/s]

Processing Cell Type: Microglia

Initializing...:  53%|█████▎    | 86/163 [01:28<01:21,  1.06s/it]

Processing Cell Type: Monocytes

Initializing...:  53%|█████▎    | 87/163 [01:29<01:26,  1.13s/it]

Processing Cell Type: Motor neurons

Initializing...:  54%|█████▍    | 88/163 [01:30<01:17,  1.04s/it]

Processing Cell Type: Myeloid-derived suppressor cells

Initializing...:  55%|█████▍    | 89/163 [01:31<01:07,  1.10it/s]

Processing Cell Type: Myoblasts

Initializing...:  55%|█████▌    | 90/163 [01:31<01:05,  1.12it/s]

Processing Cell Type: Myocytes

Initializing...:  56%|█████▌    | 91/163 [01:33<01:14,  1.03s/it]

Processing Cell Type: Myoepithelial cells

Initializing...:  56%|█████▋    | 92/163 [01:33<01:06,  1.08it/s]

Processing Cell Type: Myofibroblasts

Initializing...:  57%|█████▋    | 93/163 [01:34<00:57,  1.21it/s]

Processing Cell Type: Müller cells

Initializing...:  58%|█████▊    | 94/163 [01:35<01:03,  1.08it/s]

Processing Cell Type: NK cells

Initializing...:  58%|█████▊    | 95/163 [01:37<01:15,  1.11s/it]

Processing Cell Type: Natural killer T cells

Initializing...:  59%|█████▉    | 96/163 [01:38<01:08,  1.03s/it]

Processing Cell Type: Neural stem/precursor cells

Initializing...:  60%|█████▉    | 97/163 [01:39<01:08,  1.04s/it]

Processing Cell Type: Neuroblasts

Initializing...:  60%|██████    | 98/163 [01:40<01:06,  1.03s/it]

Processing Cell Type: Neuroendocrine cells

Initializing...:  61%|██████    | 99/163 [01:40<01:00,  1.06it/s]

Processing Cell Type: Neurons

Initializing...:  61%|██████▏   | 100/163 [01:44<01:59,  1.89s/it]

Processing Cell Type: Neutrophils

Initializing...:  62%|██████▏   | 101/163 [01:46<01:43,  1.67s/it]

Processing Cell Type: Noradrenergic neurons

Initializing...:  62%|██████▏   | 101/163 [01:46<01:05,  1.06s/it]

KeyboardInterrupt: